version: "2.1"

services:
  huginn:
    image: huginn/huginn
    restart: always
    environment:
      DO_NOT_SEED:  1
      DATABASE_URL: postgres://postgres:d3d529137c5e9ca341299fd30294e558@db:5432/huginn
    env_file: huginn.env
		labels:
      - "traefik.backend=huginn"
      - "traefik.frontend.rule=Host:${HUGINN_DOMAIN}"
  db:
    image: postgres:9.5-alpine
    restart: always
    volumes:
      - /db:/var/lib/postgresql/data
      - ./backup:/backup
    environment:
      POSTGRES_PASSWORD: d3d529137c5e9ca341299fd30294e558
      POSTGRES_DB:       huginn
  https:
    image: traefik
    restart: always
    command: --docker
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/acme.json:/acme.json
